---
title: "R journal examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ceac}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>",
fig.width = 6
)
```

```{r setup, results='hide', message=FALSE, warning=FALSE, echo=FALSE}
library(BCEA)
library(dplyr)
library(reshape2)
library(ggplot2)
library(purrr)
```


```{r eval = FALSE, echo=FALSE}
# create output docs
# rmarkdown::render(input = "vignettes/ceac.Rmd", output_format = "pdf_document", output_dir = "vignettes")
# rmarkdown::render(input = "vignettes/ceac.Rmd", output_format = "html_document", output_dir = "vignettes")
```

## Vaccine data

```{r}
data (Vaccine)

treats <- c("Status quo", "Vaccination")
bcea_vacc <- bcea(e, c, ref = 2, interventions = treats)
```

grid of plots

```{r fig.width=10, fig.height=10}
plot(bcea_vacc)
```

summary output

```{r}
summary(bcea_vacc, wtp = 10000)
sim_table(bcea_vacc, wtp = 25000)
```

value of information

```{r}
evi.plot(bcea_vacc)

inp <- createInputs(vaccine)
EVPPI <- evppi(bcea_vacc, c("beta.1.", "beta.2."), inp$mat)
```

```{r}
info.rank(bcea_vacc, inp)
```


## Smoking example

```{r}
data(Smoking)

treats <- c("No intervention", "Self-help", "Individual counselling", "Group counselling")
bcea_smoke <- bcea(e, c, ref = 4, interventions = treats, Kmax = 500)
```

grid of plots

```{r fig.width=10, fig.height=10}
library(ggplot2)

plot(bcea_smoke)
plot(bcea_smoke, graph = "ggplot2", wtp = 250, pos = TRUE, size = rel(2), ICER.size = 2)
```

individual plots
cost-effectiveness plane

```{r}
ceplane.plot(bcea_smoke, comparison = 2, wtp = 250)

setComparisons(bcea_smoke) <- c(1,3)
ceplane.plot(bcea_smoke, wtp = 250, graph = "ggplot2")
```

other plots

```{r}
eib.plot(bcea_smoke)
contour(bcea_smoke)

# lines and colour wrong...
ceac.plot(bcea_smoke)

ib.plot(bcea_smoke)

#fix:
ceef.plot(bcea_smoke)
```

multiple simultaneous comparisons

```{r}
bcea_smoke <- multi.ce(bcea_smoke)

ceac.plot(bcea_smoke, pos = "topright")
ceaf.plot(bcea_smoke)
```

mixed strategy

```{r}
mixedAn(bcea_smoke) <- c(0.4, 0.3, 0.2, 0.1)
summary(bcea_smoke, wtp = 250)
evi.plot(bcea_smoke, graph = "ggplot", pos = "b")
```

risk aversion

```{r}
r <- c(0, 0.005, 0.020, 0.035)
CEriskav(bcea_smoke) <- r

#fix:
plot(bcea_smoke)
```


